refactor: fix ansible-test issues - unicode_literals, format string
ansible-test does not like the use of unicode_literals

```
ERROR: Found 1 no-unicode-literals issue(s) which need to be resolved:
ERROR: plugins/filter/podman_to_toml.py:6:67: do not use `unicode_literals`
```

ansible-test requires field numbering in format specs:
```
ERROR: plugins/filter/podman_to_toml.py:135:20: ansible-format-automatic-specification: Format string contains automatic field numbering specification
ERROR: plugins/filter/podman_to_toml.py:160:50: ansible-format-automatic-specification: Format string contains automatic field numbering specification
```

Signed-off-by: Rich Megginson <rmeggins@redhat.com>